//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace score.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeePerformanceMTD
    {
        public int SalesID { get; set; }
        public string sl_SalesAssociate1 { get; set; }
        public string VehicleMake { get; set; }
        public Nullable<int> MTD { get; set; }
        public string FIRSTNAME { get; set; }
        public string LASTNAME { get; set; }
        public string LOCATION { get; set; }
        public Nullable<int> SalesRank { get; set; }
    }
}
