//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace score.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesBoardAllMTD
    {
        public string FIRSTNAME { get; set; }
        public string LASTNAME { get; set; }
        public string LOCATION { get; set; }
        public string sl_SalesAssociate1 { get; set; }
        public Nullable<decimal> DAY1 { get; set; }
        public Nullable<decimal> DAY2 { get; set; }
        public Nullable<decimal> DAY3 { get; set; }
        public Nullable<decimal> DAY4 { get; set; }
        public Nullable<decimal> DAY5 { get; set; }
        public Nullable<decimal> DAY6 { get; set; }
        public Nullable<decimal> DAY7 { get; set; }
        public Nullable<decimal> DAY8 { get; set; }
        public Nullable<decimal> DAY9 { get; set; }
        public Nullable<decimal> DAY10 { get; set; }
        public Nullable<decimal> DAY11 { get; set; }
        public Nullable<decimal> DAY12 { get; set; }
        public Nullable<decimal> DAY13 { get; set; }
        public Nullable<decimal> DAY14 { get; set; }
        public Nullable<decimal> DAY15 { get; set; }
        public Nullable<decimal> DAY16 { get; set; }
        public Nullable<decimal> DAY17 { get; set; }
        public Nullable<decimal> DAY18 { get; set; }
        public Nullable<decimal> DAY19 { get; set; }
        public Nullable<decimal> DAY20 { get; set; }
        public Nullable<decimal> DAY21 { get; set; }
        public Nullable<decimal> DAY22 { get; set; }
        public Nullable<decimal> DAY23 { get; set; }
        public Nullable<decimal> DAY24 { get; set; }
        public Nullable<decimal> DAY25 { get; set; }
        public Nullable<decimal> DAY26 { get; set; }
        public Nullable<decimal> DAY27 { get; set; }
        public Nullable<decimal> DAY28 { get; set; }
        public Nullable<decimal> DAY29 { get; set; }
        public Nullable<decimal> DAY30 { get; set; }
        public Nullable<decimal> DAY31 { get; set; }
        public Nullable<decimal> MTD { get; set; }
    }
}
