//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace score.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesBoardAllMTD
    {
        public string FIRSTNAME { get; set; }
        public string LASTNAME { get; set; }
        public string LOCATION { get; set; }
        public string sl_SalesAssociate1 { get; set; }
        public string VehicleMake { get; set; }
        public Nullable<int> DAY1 { get; set; }
        public Nullable<int> DAY2 { get; set; }
        public Nullable<int> DAY3 { get; set; }
        public Nullable<int> DAY4 { get; set; }
        public Nullable<int> DAY5 { get; set; }
        public Nullable<int> DAY6 { get; set; }
        public Nullable<int> DAY7 { get; set; }
        public Nullable<int> DAY8 { get; set; }
        public Nullable<int> DAY9 { get; set; }
        public Nullable<int> DAY10 { get; set; }
        public Nullable<int> DAY11 { get; set; }
        public Nullable<int> DAY12 { get; set; }
        public Nullable<int> DAY13 { get; set; }
        public Nullable<int> DAY14 { get; set; }
        public Nullable<int> DAY15 { get; set; }
        public Nullable<int> DAY16 { get; set; }
        public Nullable<int> DAY17 { get; set; }
        public Nullable<int> DAY18 { get; set; }
        public Nullable<int> DAY19 { get; set; }
        public Nullable<int> DAY20 { get; set; }
        public Nullable<int> DAY21 { get; set; }
        public Nullable<int> DAY22 { get; set; }
        public Nullable<int> DAY23 { get; set; }
        public Nullable<int> DAY24 { get; set; }
        public Nullable<int> DAY25 { get; set; }
        public Nullable<int> DAY26 { get; set; }
        public Nullable<int> DAY27 { get; set; }
        public Nullable<int> DAY28 { get; set; }
        public Nullable<int> DAY29 { get; set; }
        public Nullable<int> DAY30 { get; set; }
        public Nullable<int> DAY31 { get; set; }
        public Nullable<int> MTD { get; set; }
    }
}
