//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace score.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SalesCommissionEntities : DbContext
    {
        public SalesCommissionEntities()
            : base("name=SalesCommissionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SalesBoardAllMTD> SalesBoardAllMTDs { get; set; }
        public virtual DbSet<EmployeePerformanceMTD> EmployeePerformanceMTDs { get; set; }
    
        public virtual int sp_EmployeePerformanceMTD_AllLocations_Calendar()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_EmployeePerformanceMTD_AllLocations_Calendar");
        }
    
        public virtual int sp_EmployeePerformanceMTD_AllLocations()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_EmployeePerformanceMTD_AllLocations");
        }
    }
}
