//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace score.Models
{
    using System;
    
    public partial class sp_ListOfSalesTeams_Result1
    {
        public string dept_code { get; set; }
        public string dept_desc { get; set; }
    }
}
